// Generated by CoffeeScript 1.4.0
(function() {
  var RoutesHome, RoutesHomePathHelper, _,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  _ = require('underscore');

  RoutesHomePathHelper = (function() {

    function RoutesHomePathHelper() {}

    RoutesHomePathHelper.prototype.root = '/';

    return RoutesHomePathHelper;

  })();

  module.exports = RoutesHome = (function() {

    function RoutesHome(app) {
      this.app = app;
      this.index = __bind(this.index, this);

      this.setupRoutes = __bind(this.setupRoutes, this);

      this.setupLocals = __bind(this.setupLocals, this);

      if (!this.app) {
        throw new Error("app parameter is required");
      }
    }

    RoutesHome.prototype.setupLocals = function() {
      return this.app.locals.routesHome = this.routesHomePathHelper = new RoutesHomePathHelper;
    };

    RoutesHome.prototype.setupRoutes = function() {
      return this.app.get('/', this.index);
    };

    RoutesHome.prototype.index = function(req, res) {
      return res.render('index', {
        controllerName: "home"
      });
    };

    return RoutesHome;

  })();

}).call(this);
